blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('<slug>/', views.detail_blog_view, name='detail')
]

my_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', 'blog')),
    path('tinymce/', include('tinymce.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.utils.text import slugify


class Post(models.Model):
    title = models.CharField(max_length=250, null= False, blank = False)
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='blog_posts')
    intro = models.CharField(max_length=100, blank=True)
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    category = models.CharField(max_length = 20)
    imageId = models.CharField(max_length= 200, blank = True)
    slug = models.SlugField(blank= True, unique= True)

    
    def _get_unique_slug(self):
        slug = slugify(self.title)
        unique_slug = slug
        num = 1
        while Post.objects.filter(slug=unique_slug).exists():
            unique_slug = '{}-{}'.format(slug, num)
            num += 1
        return unique_slug
 
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = self._get_unique_slug()
        super().save(*args, **kwargs)
        
    def __str__(self):
        return self.title

    

class Email(models.Model):
    email = models.EmailField()

blog/views.py
from django.shortcuts import render, get_object_or_404
from operator import attrgetter
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from .models import Post, Email
from django.http import HttpResponse
# Create your views here.

def homepage(request):

    posts = {}

    blog_posts = sorted(Post.objects.all(),key = attrgetter('publish'), reverse = True)

    #Pagination

    page = request.GET.get('page', 1)

    paginator = Paginator(blog_posts, 3)

    
    if paginator.num_pages == 1:
        pass
    else:
        try:
            blog_posts = paginator.page(page)
        except PageNotAnInteger:
            blog_posts = paginator.page(1)
        except EmptyPage:
            blog_posts = paginator.page(paginator.num_pages)\

    if request.method == "POST":
        email = request.POST.get('email')
        
        email_add = Email(email = email)

        email_add.save()

    posts['blog_posts'] = blog_posts

    return render(request, 'index.html', posts)

def detail_blog_view(request, slug):
    
    context = {}

    blog_post = get_object_or_404(Post, slug=slug)

    context['blog_post'] = blog_post

    return render(request, 'content.html', context)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Garv Nanwani's Space - A Platform To Share My Ideas And Thoughts</title>
    <meta name="Description" content="" >

    <link rel="shortcut icon" href="{% static './assets/favicon/favicon.ico'  %}" type="image/x-icon" />
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="{% static 'css/all.css' %} " />

    <!-- ------------ AOS Library ------------------------- -->
    <link rel="stylesheet" href=" {% static 'css/aos.css' %} " />

    <!-- Custom Style   -->
    <link rel="stylesheet" href=" {% static 'css/Style.css' %} " />

    {% block css %}

    {% endblock css %}

  </head>

  <body>
    <!-- ----------------------------  Navigation ---------------------------------------------- -->

    <nav class="nav">
      <div class="nav-menu flex-row">
        <div class="nav-brand">
          <a href="/" class="text-gray nav-tab">Home</a>
        </div>
        </div>
      </div>
    </nav>

    <!-- ------------x---------------  Navigation --------------------------x------------------- -->

    <!------------------------ Site Title ---------------------->

    <main>

      <!------------x----------- Site Title ----------x----------->

    {% block body %}

    {% endblock %}


        <!-- --------------------------- Footer ---------------------------------------- -->

    <footer class="footer">
      <div class="container">
        <div class="about-us" data-aos="fade-right" data-aos-delay="200">
          <h2>About me</h2>
          <p class="light-text">
            My name is Garv nanwani, I am a second year engineering undergraduate student. My field of interests are coding, designing and psychology.
          </p>
        </div>
        <div class="newsletter" data-aos="fade-right" data-aos-delay="200">
          <h2>Newsletter</h2>
          <p class="light-text">Stay updated with my latest post</p>
          <div class="form-element">
            <form method="post" action="/" onsubmit="myFunction()">
              {% csrf_token %}
            <input type="text" placeholder="Email"  style="outline: none;" name="email"/><button class="letter-btn" type="submit"
              ><i class="fas fa-chevron-right"></i
            ></button>
            </form>
          </div>
        </div>
        <div class="instagram" data-aos="fade-left" data-aos-delay="200">
          <a href="https://www.instagram.com/garv_nanwani/" target="_blank"> <h2>My Instagram</h2> </a>
          <div class="flex-row">
            <img src="{% static './assets/instagram/insta4.jpg' %}" alt="insta1" />
            <img src="{% static './assets/instagram/insta5.jpg' %}" alt="insta2" />
            <img src="{% static './assets/instagram/insta2.jpg' %}" alt="insta3" />
          </div>
          <div class="flex-row">
            <img src="{% static './assets/instagram/insta6.jpg' %}" alt="insta4" />
            <img src="{% static './assets/instagram/insta3.jpg' %}" alt="insta5" />
            <img src="{% static './assets/instagram/insta7.jpg' %}" alt="insta6" />
          </div>
        </div>
        <div class="follow" data-aos="fade-left" data-aos-delay="200">
          <h2>Follow me</h2>
          <p  class="light-text">I would love to hear from you</p>
          <div>
            <a href="https://www.linkedin.com/in/garvnanwani/" target="_blank"><i class="fab fa-linkedin-in"></i></a>
            <a href="https://twitter.com/thisisgarv/" target="_blank"><i class="fab fa-twitter"></i></a>
            <a href="https://www.instagram.com/garv_nanwani/" target="_blank"> <i class="fab fa-instagram"></i></a>
            <a href="https://www.youtube.com/channel/UC3U43TM2nQz1doUxUAVuI9w?view_as=subscriber/" target="_blank"><i class="fab fa-youtube"></i></a>
          </div>
        </div>
      </div>
      <div class="rights flex-row">
        <h4 class="text-gray">
          Garv nanwani Blog
        </h4>
      </div>
      <div class="move-up">
        <span><i class="fas fa-arrow-circle-up fa-2x"></i></span>
      </div>
    </footer>

</main>
    <!-- -------------x------------- Footer --------------------x------------------- -->

    <!-- Jquery Library file -->
    <script src=" {% static 'js/Jquery3.4.1.min.js' %} "></script>

    <!-- ------------ AOS js Library  ------------------------- -->
    <script src=" {% static 'js/aos.js' %} "></script>

    <script>


      function myFunction(event) {
        alert("The form was submitted");
      }

      if ( window.history.replaceState ) {
          window.history.replaceState( null, null, window.location.href );
      }


    </script>

    <!-- Custom Javascript file -->
    <script src=" {% static 'js/main.js' %} "></script>
  </body>
</html>

templates/content.html
{% extends 'base.html' %}
{% block css %}

<style>

body {
  margin: 0%;
  box-sizing: border-box;
  overflow-x: hidden;
}

:root {
  /*      Theme colors        */
  --text-gray: #3f4954;
  --text-light: #686666da;
  --bg-color: #0f0f0f;
  --white: #ffffff;
  --midnight: #104f55;
  --orange: #a26147;

  /* gradient color   */
  --sky: -webkit-linear-gradient(120deg, #a1c4fd 0%, #c2e9fb 100%);

  /*      theme font-family   */
  --Abel: "Abel", cursive;
  --Anton: "Anton", cursive;
  --Josefin: "Josefin", cursive;
  --Lexend: "Lexend", cursive;
  --Livvic: "Livvic", cursive;
}

.nav {
  border: 2px solid black;
}

#heading {
  display: flex;
  justify-content: center;
  align-items: center;
  width: 100% !important;
  margin: 0 auto;
  margin-top: 16px;
}

#post-body{
  margin: 16px 90px 40px 90px;
  border: 2px solid black;
  padding: 0 30px;
}

#content{
  font-size: 28px;
  color:black;
}

.nav .social {
  padding: 1.4rem 0;
}

.nav .social i {
  padding: 0 0.2rem;
}

.nav .social i:hover {
  color: rgba(162, 97, 71) !important;
}

.blog-img{
  float: left;
  margin-top: 28px;
  margin-right: 28px;
  margin-bottom: 20px;
  width:45%;
  height: 50%;
  border-radius: 25px;
}

.info{
  margin-bottom: 50px;
  text-align: left;
}

.author{
  font-size: 24px;
  color: black;
  padding-left: 90px;
}

@media only screen and (min-width: 768px) {
    
    h1{
        padding-left: 35px;
        padding-right: 35px;
        text-align: center;
    }

    .blog-img{
      width: 500px;
      height: 300px;
    }

    #post-body {
      font-size: 21px;
    }

}

@media only screen and (max-width: 770px) {

  body{
    max-width: 100vw !important;
  }

  #heading{
    display: flex;
    width:100vh;
    justify-content: center;
    margin: 0 auto !important;
    overflow-wrap: normal;
    padding-left: 22px;
    padding-right: 22px;
    font-size: 32px !important;
  }

  h1{
    font-size: 23px;
    padding-right: 43px;
    text-align: center;
  }
  
  #post-body{
    margin: 2px 7px 50px 7px;
    padding-left: 12px;
    padding-right: 12px;
  }

  #content{
    font-size: 18px !important;
  }

  .info{
    margin-bottom: 30px;
  }

  .author{
    font-size: 15px;
    padding-left: 7px;
  }

  .blog-img{
    
    display: block;

  }

}

</style>

{% endblock css %}


{% block body %}

<div id="heading">
    <h1>{{ blog_post.title}}</h1>
</div>

<div class="info">
  <p class="author">Posted By {{ blog_post.author }} on {{ blog_post.publish }} </p>
</div>

<div id="post-body" style="word-break: break-word;">
  <img src="https://drive.google.com/uc?id={{ blog_post.imageId }}" alt="blog related image" class="blog-img">
    <p id="content">{{ blog_post.body|safe }}</p>
</div>


{% endblock body %}

    

templates/index.html
{% extends 'base.html' %}

{% load static %}


{% block css %}

<style>

ul{
  display: flex;
  justify-content: centre;
  margin: 0 auto;
  text-align: center;
}
.pagination {
    text-align: center;
    margin-top: 1em;
}

.pagination a {
    text-decoration: none;
}

.pagination-number {
    padding: 0.5em 0.8em;
    border-radius: 2px;
    color: #fff;
    background-color: #6D85C7;
}

.pagination-number:hover,
.pagination-current {
    background-color: #3354AA;
}

.pagination-action {
    margin: 0 0.1em;
    display: inline-block;
    padding: 0.5em 0.5em;
    color: #B9B9B9;
    font-size: 1.3em;
}

.pagination-action:hover,
.pagination-previous,
.pagination-next {
    color: #3354AA;
}

.title{
  color: black;
}

</style>

{% endblock css %}

{% block body %}

    <!----------------------------- Main Site Section ------------------------------>

    <!-- banner -->

    <section class="site-title">
      <div class="site-background" data-aos="fade-up" data-aos-delay="100">
        <h3 class="site-name">GARV'S SPACE</h3>
        <h1 class="site-name">A PLATFORM TO SHARE MY IDEAS AND THOUGHTS</h1>
      </div>
    </section>

    <!-- banner -->

      <!-- ---------------------- Site Content -------------------------->

      <section class="container">
      <div class="name" data-aos="fade-right">
        <h1>Blog Articles</h1>
      </div>
        <div class="site-content">
          <div class="posts">
            {% for post in blog_posts %}
            <div class="post-content" data-aos="zoom-in" data-aos-delay="200">
              <div class="post-image">
                <div>
                  <a href="{% url 'blog:detail' post.slug %}">
                  <img
                    src="https://drive.google.com/uc?id={{ post.imageId }}"
                    class="img" id="blog-img"
                    alt="blog1"
                  />
                  </a>
                </div>
                <div class="post-info flex-row">
                  <span
                    ><i class="fas fa-user"></i
                    >&nbsp;&nbsp;{{ post.author }}</span
                  >
                  <span>
                    <i class="fa fa-list-alt" aria-hidden="true"></i>
                    &nbsp;&nbsp;{{ post.category }}</span>
                  <span
                    ><i class="fas fa-calendar-alt"></i
                    >&nbsp;&nbsp;{{ post.publish }}</span
                  >
                  
                </div>
              </div>
              <div class="post-title">
                <a href="{% url 'blog:detail' post.slug %}" class="title"
                  >{{ post.title}}</a
                >
                <p class="intro light-text"> 
                  {{post.intro}}......
                </p>
                <a type="button" id = "read-more" class="btn post-btn" href="{% url 'blog:detail' post.slug %}">
                  Read More &nbsp; <i class="fas fa-arrow-right" target= '_blank'></i>
                </a>
              </div>
            </div>
            <hr />
          {% endfor %}

          </div>
          {% include 'paginator.html'%}

        </div>
      </section>

      <!-- -----------x---------- Site Content -------------x------------>

    <!---------------x------------- Main Site Section ---------------x-------------->

    {% endblock %}

templates/paginator.html
<!-- FILTERED Pagination -->
<div class="d-flex flex-column m-auto pagination mt-5">
    <nav aria-label="Page navigation">
    <ul class="pagination pg-grey justify-content-center">

        {% if blog_posts.has_previous %}
            <li class="page-item">
              <a class="page-link" href="?{% if query %}q={{query}}&{% endif %}page={{ blog_posts.previous_page_number }}">&laquo; Previous</a>
            </li>
        {% endif %}
    
        {% for i in blog_posts.paginator.page_range %}
            {% if blog_posts.number == i %}
                <li class="page-item active"><a class="page-link">{{ i }}</a></li>
            {% else %}
                <li class="page-item" ><a class="page-link" href="?{% if query %}q={{query}}&{% endif %}page={{ i }}">{{ i }}</a></li>
            {% endif %}
        {% endfor %}
        
        {% if blog_posts.has_next %}
            <li class="page-item">
              <a class="page-link" href="?{% if query %}q={{query}}&{% endif %}page={{ blog_posts.next_page_number }}">Next</a>
            </li>
            <li class="page-item">
              <a class="page-link"  href="?{% if query %}q={{query}}&{% endif %}page={{ blog_posts.paginator.num_pages }}">Last &raquo;</a>
            </li>
        {% endif %}
    </ul>
    </nav>
    </div>
    <!-- end pagination-->